apiVersion: apps/v1
kind: Deployment
metadata:
  name: mmanagementdb
spec:
  replicas: 1
  selector:
     matchLabels:
       app: mmanagementdb
  template:
    metadata:
      labels:
        app: mmanagementdb
    spec:
      terminationGracePeriodSeconds: 30
      hostname: mssqlinst
      securityContext:
        fsGroup: 10001
      containers:
      - name: mmanagementdb
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mmanagementmssql
              key: pwd
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mmanagementdb-data
---
apiVersion: v1
kind: Service
metadata:
  name: mmanagementdb
spec:
  selector:
    app: mmanagementdb
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer